Config:
  Default: default
  #普通玩家的组
  DataBase:
    Type: sqlite
    #填写sqlite或mysql(还没做好)
    #填写mysql需填写下方连接信息
    #MySQL:
      #addr: 'jdbc:mysql://127.0.0.1:3306/vipsystem'
      #jdbc:mysql://地址:端口/库名
      #user: 'root'
      #mysql用户名
      #pwd: 'pwdhere'
      #mysql密码