Version: 1.7
Config:
  Default: 'default'
  #普通玩家的组，如果你需要在玩家vip到期后返回没有vip时的组，请填写 #last
  UUID-Mode: false
  KeyWord: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890
  DataBase:
    Type: sqlite
    #填写sqlite或mysql
    #填写mysql需填写下方连接信息
    MySQL:
      addr: 127.0.0.1
      #mysql地址
      port: 3306
      #端口
      base: minecraft
      #库名
      user: 'root'
      #mysql用户名
      pwd: 'pwdhere'
      #mysql密码