Config:
  Default: default
  #普通玩家的组
  KeyWord: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890
  DataBase:
    Type: sqlite
    #填写sqlite或mysql(还没做好)
    #填写mysql需填写下方连接信息
    #MySQL:
      addr: 127.0.0.1
      #mysql地址
      port: 3306
      #端口
      base: minecraft
      #库名
      user: 'root'
      #mysql用户名
      pwd: 'pwdhere'
      #mysql密码